### ISSUE TITLE
Add Command Line Support

### ISSUE THREAD

**Issue by kwent** [theodi/csvlint.rb#128]
# Add Command Line Support

Similar as https://github.com/Clever/csvlint

**Comment by adamc00** [comment]
@kwent, the library csvlint.rb already shops with a command line utility (see the bin directory). It is installed for you when you follow the installation directions in README.md. Is that what you are looking for?

**Comment by kwent** [comment]
@adamc00 Oh nice i did not see that ! Well maybe you should complete the README and indicate this. With the --help. Params and an example how to use it ?

**Comment by adamc00** [comment]
Hi @kwent, I'm not actually a maintainer of this project just a fellow user. Why not fork this project, update README.md, and submit a pull request to include your documentation improvement? The project team here have applied my own pull requests so I'm sure they'd appreciate one from you.

**Comment by Floppy** [comment]
Oh, yes, a section on command-line use would be great! We'll add it to our list, but if anyone fancies sending in a PR, that would be great. We're not getting much time on this at the moment.

**Comment by pezholio** [comment]
I'll have a go at this now
