### ISSUE TITLE
CSV on the web support

### ISSUE THREAD

**Issue by Floppy** [theodi/csvlint.rb#141]
From @jenit: 

Specs are at: 

  http://w3c.github.io/csvw/syntax/ 
  http://w3c.github.io/csvw/metadata/ 

The examples at: 

  http://w3c.github.io/csvw/csv2json/#examples  

are particularly useful. 

There are tests are described at: 

  http://www.w3.org/2013/csvw/tests/ 

and are in Github at: 

  https://github.com/w3c/csvw/tree/gh-pages/tests  

There’s a manifest in JSON at: 

  https://github.com/w3c/csvw/blob/gh-pages/tests/manifest.jsonld 

which points to the manifest for the validation tests (which are the only ones I think we have to care about) which is at: 

  https://github.com/w3c/csvw/blob/gh-pages/tests/manifest-validation.jsonld  

Creating something that maps that test manifest into whatever format tests are needed for csvlint would be good. 

I suspect that you will want to distinguish between validation based on datapackage and validation based on CSV on the Web metadata: there are many similarities but they’re not identical.

**Comment by JeniT** [comment]
I have started to implement this in the feature-csvw-validation branch
