### ISSUE TITLE
Get total rows number about the CSV file that was validated

### ISSUE THREAD

**Issue by kwent** [theodi/csvlint.rb#143]
Hi,

Similar to the example below, i would love to be able to know how many rows my csv is without reparsing all the files via `csv` ruby library ...

```ruby
# get some information about the CSV file that was validated
validator.encoding
validator.content_type
validator.extension
**validator.rows**
```

Regards,

**Comment by pezholio** [comment]
We already count the rows internally, so this should be pretty trivial. We're currently refactoring how the internals of CSVlint work quite considerably, but will bear this in mind for the refactoring work :+1:

**Comment by kwent** [comment]
Awesome !

**Comment by kwent** [comment]
@pezholio An idea of ETA ?
