### ISSUE TITLE
Include field name with error

### ISSUE THREAD

**Issue by wachunga** [theodi/csvlint.rb#161]
When using the cli with a schema, the error output only includes the column number, but not the field name (except in [one case](https://github.com/theodi/csvlint.rb/blob/master/lib/csvlint/field.rb#L60)).

Instead of:
```
1. missing_value. Row: 10,43.
```

I suggest something like:
```
1. ACCOUNT_NO: missing_value. Row: 10,43.
```

Would greatly facilitate debugging.

**Comment by pezholio** [comment]
Thanks for the suggestion. I'm actually looking at refactoring the CLI this week, so will look at this ASAP :+1:
