### ISSUE TITLE
How to access the csv2rdf functionality.

### ISSUE THREAD

**Issue by l00mi** [theodi/csvlint.rb#191]
I stumbled upon this through http://w3c.github.io/csvw/publishing-snapshots/PR-earl/earl.html#subj_1. Thats why am looking for the csv2rdf functionality here?

Wrong repo, or did I not look thoroughly enough?

**Comment by pezholio** [comment]
Hey, this is in a separate project - see https://github.com/theodi/csv2rdf

**Comment by l00mi** [comment]
I see, thanks! Might ask to update http://w3c.github.io/csvw/publishing-snapshots/PR-earl/earl.html#subj_1
