### ISSUE TITLE
Periodic warning about non-standard dialects, which goes away upon clicking “validate again”

### ISSUE THREAD

**Issue by andylolz** [theodi/csvlint.rb#197]
![screen shot 2017-03-20 at 14 58 31](https://cloud.githubusercontent.com/assets/464193/24105778/dbe8518a-0d7d-11e7-957d-307b16ada338.png)

This warning reappears nightly, leaving my badge showing CSV warnings:
[![CSV Validation](https://csvlint.io/validation/58cc177e3566300004000061.svg?revalidate=false)](https://csvlint.io/validation/58cc177e3566300004000061)

However, when I click to revalidate, the warning goes away.

**Comment by quadrophobiac** [comment]
Hi @andylolz I've moved this issue to https://github.com/theodi/csvlint/issues/344 because - for now - it seems more apt to file against the CSVlint service rather than the CSVlint library

**Comment by andylolz** [comment]
Yeah, that’s fair enough!
