### ISSUE TITLE
csvlint is missing libcurl.dll

### ISSUE THREAD

**Issue by matt-jk** [theodi/csvlint.rb#228]
### Expected Behaviour
> The utility installs properly from the `gem install csvlint`, but the expected behavior is it should launch, but it doesn't. I tried googling a mistake I might have made but it isn't obvious.

### Current Behaviour (for problems)
> It fails with the following error:
`C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ffi-1.11.1-x64-mingw32/lib/ffi/library.rb:145:in block in ffi_lib': Could not op (LoadError)libcurl': The specified module could not be found.`
`.`
`Could not open library 'libcurl.dll': The specified module could not be found.`
`.`
`Could not open library 'libcurl.so.4': The specified module could not be found.`
`.`
`Could not open library 'libcurl.so.4.dll': The specified module could not be found.`

### Steps to Reproduce (for problems)
> after installing, simply type `csvlint` at the command line and that causes the error

### Your Environment
> Windows 10:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134

Version of Ruby:
`D:\>ruby -v`
`ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]`

**Comment by adamc00** [comment]
Windows does not include `libcurl.dll` by default. It is part of the `curl` command and can be installed from https://curl.haxx.se/windows/.

Here's an [example of the same problem](https://stackoverflow.com/questions/39377541/how-to-solve-libcurl-not-found-with-rails-on-windows) in a different project. The solution listed there should help you.

**Comment by matt-jk** [comment]
I'll give it a try and close the issue, thank you indeed!

**Comment by matt-jk** [comment]
Update: I downloaded `curl-7.65.0_1-win64-mingw.zip` from https://curl.haxx.se/windows.

Unzip it and navigate to the /bin folder, and rename `libcurl-x64.dll` to `libcurl.dll`

`copy libcurl.dll C:\Ruby25-x64\bin`

That did the trick.
